version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/venv
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DB_HOST=postgres_flask
      - DB_PORT=5432
      - DB_NAME=flaskdb
      - DB_USER=user
      - DB_PASSWORD=userpassword
    depends_on:
      - postgres_flask

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend

  postgres_flask:
    image: postgres:latest
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_DB: flaskdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
